-- 3) 문제
CREATE TABLE DEPT (
    DNO INT PRIMARY KEY,
    DNAME VARCHAR(50) NOT NULL
);

-- 2. EMP 테이블 생성
CREATE TABLE EMP (
    ENO INT PRIMARY KEY,
    ENAME VARCHAR(50) NOT NULL,
    SAL INT NOT NULL,
    DNO INT,
    FOREIGN KEY (DNO) REFERENCES DEPT(DNO)
);
SELECT e.DNO, d.DNAME, MAX(e.SAL) AS 최고급여
FROM EMP e
JOIN DEPT d ON e.DNO = d.DNO
WHERE e.DNO IN (10, 30)
GROUP BY e.DNO, d.DNAME
HAVING MAX(e.SAL) >= 3000;









